name: CI

on:
  push:
    branches: ["main"]

jobs:
  builds:
    run-on: ubuntu-latest

    steps:

      - name: Checkout SCM
        uses: action/checkout@v4    

      - name: Check
        run: ls